name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/api-sql
            # Verificar el estado del repositorio
            git status
            # Resetear cualquier cambio local
            git reset --hard
            # Hacer pull de la última versión de la rama main
            git pull origin main
            # Construir la imagen de Docker
            docker build -t my-node-app:latest .
            # Detener y eliminar el contenedor en ejecución, si existe
            docker stop my-node-container || true
            docker rm my-node-container || true
            # Ejecutar el nuevo contenedor
            docker run -d --name my-node-container -p 80:3000 my-node-app:latest
           EOF

